### ISSUE TITLE
Java errors reading gtex.v8.transcript.mean.tsv.gz file

### ISSUE THREAD

**Issue by fmurgia** [pmglab/KGGSEE#9]
Hi,

I'm trying using KGGSEE pipeline but I found some errors during reading gtex.v8.transcript.mean.tsv.gz file. 

I'm reporting here the error:

@----------------------------------------------------------@
|        KGGSEE        |     v1.0     |     15/Apr./2022   |
|----------------------------------------------------------|
|        (C)2019          Miaoxin Li,  limx54@163.com      |
|----------------------------------------------------------|
|  For documentation, citation & bug-report instructions:  |
|                  http://pmglab.top/kggsee                |
@----------------------------------------------------------@
Effective settings:
--nt 10 \
--sum-file test_4_pcga.txt.gz \
--chrom-col CHR \
--pos-col POS \
--p-col pvalue \
--gene-finemapping \
--eqtl-file ../Tools/kggsse/kggsee/resources/gtex.v8.gene.mean.tsv.gz \
--filter-eqtl-p 0.01 \
--vcf-ref ../Reference_data/1KG_p3_v5/VCF/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz \
--out geneAssoceQTL \
--db-gene refgene,gencode \
--only-hgnc-gene \
--p-value-cutoff 0.05 \
--multiple-testing bonf \
--regions-out chr6:27477797-34448354 \
--expression-file ../Tools/kggsse/kggsee/resources/gtex.v8.transcript.mean.tsv.gz
java.lang.NumberFormatException: For input string: "Name"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:543)
        at org.cobi.kggsee.controller.PValueReader.readeQTLPValuesFastAFormat(Unknown Source)
        at org.cobi.kggsee.CUIApp.parseeQTLPValueFile(Unknown Source)
        at org.cobi.kggsee.CUIApp.process(Unknown Source)
        at org.cobi.kggsee.CUIApp.main(Unknown Source)
java.lang.Exception: java.lang.NumberFormatException: For input string: "Name" when parsing at line 2: Name     Adipose-Subcutaneous.mean       Adipose-Subcutaneous.SE Adipose-VisceralOmentum.mean    Adipose-VisceralOmentum.SE    AdrenalGland.mean        AdrenalGland.SE Artery-Aorta.mean       Artery-Aorta.SE Artery-Coronary.mean    Artery-Coronary.SE      Artery-Tibial.mean      Artery-Tibial.SE        Bladder.mean    Bladder.SE      Brain-Amygdala.mean   Brain-Amygdala.SE        Brain-AnteriorcingulatecortexBA24.mean  Brain-AnteriorcingulatecortexBA24.SE    Brain-Caudatebasalganglia.mean  Brain-Caudatebasalganglia.SE    Brain-CerebellarHemisphere.mean Brain-CerebellarHemisphere.SE Brain-Cerebellum.mean    Brain-Cerebellum.SE     Brain-Cortex.mean       Brain-Cortex.SE Brain-FrontalCortexBA9.mean     Brain-FrontalCortexBA9.SE       Brain-Hippocampus.mean  Brain-Hippocampus.SE    Brain-Hypothalamus.mean Brain-Hypothalamus.SE  Brain-Nucleusaccumbensbasalganglia.mean Brain-Nucleusaccumbensbasalganglia.SE   Brain-Putamenbasalganglia.mean  Brain-Putamenbasalganglia.SE    Brain-Spinalcordcervicalc-1.mean        Brain-Spinalcordcervicalc-1.SEBrain-Substantianigra.mean       Brain-Substantianigra.SE        Breast-MammaryTissue.mean       Breast-MammaryTissue.SE Cells-Culturedfibroblasts.mean  Cells-Culturedfibroblasts.SE    Cells-EBV-transformedlymphocytes.mean   Cells-EBV-transformedlymphocytes.SE    Cervix-Ectocervix.mean  Cervix-Ectocervix.SE    Cervix-Endocervix.mean  Cervix-Endocervix.SE    Colon-Sigmoid.mean      Colon-Sigmoid.SE        Colon-Transverse.mean   Colon-Transverse.SE     Esophagus-GastroesophagealJunction.mean        Esophagus-GastroesophagealJunction.SE   Esophagus-Mucosa.mean   Esophagus-Mucosa.SE     Esophagus-Muscularis.mean       Esophagus-Muscularis.SE FallopianTube.mean      FallopianTube.SE      Heart-AtrialAppendage.mean       Heart-AtrialAppendage.SE        Heart-LeftVentricle.mean        Heart-LeftVentricle.SE  Kidney-Cortex.mean      Kidney-Cortex.SE        Kidney-Medulla.mean     Kidney-Medulla.SE       Liver.mean    Liver.SE Lung.mean       Lung.SE MinorSalivaryGland.mean MinorSalivaryGland.SE   Muscle-Skeletal.mean    Muscle-Skeletal.SE      Nerve-Tibial.mean       Nerve-Tibial.SE Ovary.mean      Ovary.SE        Prostate.mean   Prostate.SE   Skin-NotSunExposedSuprapubic.mean        Skin-NotSunExposedSuprapubic.SE Skin-SunExposedLowerleg.mean    Skin-SunExposedLowerleg.SE      SmallIntestine-TerminalIleum.mean       SmallIntestine-TerminalIleum.SE Spleen.mean     Spleen.SE      Testis.mean     Testis.SE       Thyroid.mean    Thyroid.SE      Uterus.mean     Uterus.SE       Vagina.mean     Vagina.SE
        at org.cobi.kggsee.controller.PValueReader.readeQTLPValuesFastAFormat(Unknown Source)
        at org.cobi.kggsee.CUIApp.parseeQTLPValueFile(Unknown Source)
        at org.cobi.kggsee.CUIApp.process(Unknown Source)
        at org.cobi.kggsee.CUIApp.main(Unknown Source)

I get same error using different Java version. 

Any idea to solve the trouble?

Best,

Federico

**Comment by pmglab** [comment]
The parameter "--eqtl-file" is used to specify an eQTL file instead of a gene expression profile file (gtex.v8.gene.mean.tsv.gz). You can find the eQTL files under [this folder](https://mailsysueducn-my.sharepoint.com/personal/limiaoxin_mail_sysu_edu_cn/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Flimiaoxin%5Fmail%5Fsysu%5Fedu%5Fcn%2FDocuments%2Ftools%2Fkggsee%2Fresources%2Fhg19%2Feqtl).

Best,

PMGLab

**Comment by pmglab** [comment]
@fmurgia 

The parameter "--eqtl-file" is used to specify an eQTL file instead of a gene expression profile file (gtex.v8.gene.mean.tsv.gz). You can find the eQTL files under [this folder](https://mailsysueducn-my.sharepoint.com/personal/limiaoxin_mail_sysu_edu_cn/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Flimiaoxin%5Fmail%5Fsysu%5Fedu%5Fcn%2FDocuments%2Ftools%2Fkggsee%2Fresources%2Fhg19%2Feqtl).

Best,

PMGLab
